[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/airbnb-ical"
  to = "/.netlify/functions/airbnb-ical"
  status = 200

[[redirects]]
  from = "/api/send-booking-email"
  to = "/.netlify/functions/send-booking-email"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
